[package]
name = "ibara_parser"
version = "0.1.0"
authors = ["Mirai Towa <mkut.at@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.12.0"
ego-tree = "0.6.2"